### ISSUE TITLE
How to get single content

### ISSUE THREAD

**Issue by albinlang** [ribalnasr/ng-flamelink#1]
I use the following code in my TS to get my array of portfolio-items and load a spinner while waiting for async data:

```
  constructor(private content: FLContent) { }

  loading = false;

  public portfolio = this.content.valueChanges({
    schemaKey: 'portfolio',
    orderBy: { field: 'company', order: 'asc' }
  }).pipe(first(), finalize(() => this.loading = false));

  ngOnInit() {
    this.loading = true;
  }

}
```
My question is how would I get content of type single? When using the same approach as above I only get `[object Object]`

**Comment by ribalnasr** [comment]
hi @albinlang, sorry for the late reply,
the same approach is used to get a single content.
however note that if the schema type is single, the valueChanges({schemaKey: 'singleExample'}) will not return an array of documents, instead it will directly return an object of the single document. 

let me know if this doesn't answer your question.

**Comment by albinlang** [comment]
How can I subscribe single content in the template using the async pipe?

**Comment by ribalnasr** [comment]
this is more of an angular question but i'll gladly let you know below how how i'd do it:

component.ts:
```ts
@Component(...)
export class ComponentName {
    public about = this.content.valueChanges({schemaKey: 'about'});
    constructor(private content: FLContent) { }
}
```

component.html:
```html
<div *ngIf="about | async as about">
     <h1>{{ about.title }}</h1>
     <p>{{ about.description }}</p>
</div>
```

**Comment by albinlang** [comment]
Thank you very muck for your response. 

In my ts I have:
`  constructor(private content: FLContent) { }

  public about = this.content.valueChanges({schemaKey: 'about'});`

and in my HTML I have:
`    <div class="row" *ngIf="about | async as about">
			<div class="col-md-12" [innerHtml]="about.content | mdToHtml">
      </div>`

The mdToHtml-pipe is a pipe that transform markdown from Flamelink to html using the marked library.

mdToHtml-pipe:
`import { Pipe, PipeTransform } from '@angular/core';
import * as marked from 'marked';

@Pipe({
  name: 'mdToHtml'
})
export class MdToHtmlPipe implements PipeTransform {

  transform(value: any, args?: any[]): any {
    return marked(value || '');
  }

}`

This works but VS-code gives me the following error on my innerHtml-value:
`Identifier 'content' is not defined. 'unknown' does not contain such a member`

**Comment by ribalnasr** [comment]
interesting, my vs-code doesn't give me these warning for html files. i'd like to know how did you get this working... however i believe the following will solve your issue:

when using .valueChanges(...) you can add the type of result you're expecting like the examples below:

```ts
export interface About {
     title: string;
     content: string;
}

export interface PressRelease {
    title: string;
    link: string;
}

@Component(...)
export class ComponentName {

     // Single Content Example
    public about = this.content.valueChanges<About>({schemaKey: 'about'}); 

    // Collection Example
    public pressReleases = this.content.valueChanges<PressRelease[]>({schemaKey: 'pressReleases'});
    constructor(private content: FLContent) { }
}
```

**Comment by albinlang** [comment]
Thank you, you have been very helpful.

Could ng-flamelink be used if I wanted to query batches of objects for pagination, and if so, how?
